### ISSUE TITLE
I am confused about the code

### ISSUE THREAD

**Issue by liuzh-buaa** [uwdata/fast-kde#6]
https://github.com/uwdata/fast-kde/blob/f94f0215f2a8e2c36944883eb71c639b8a292844/src/deriche.js#L133-L136
https://github.com/uwdata/fast-kde/blob/f94f0215f2a8e2c36944883eb71c639b8a292844/src/deriche.js#L193

1. I think that the number of parameters mismatches between the definition and usage.
2. Does 'c.sum_causal' and 'c.sigma' matter?

Thank you!

**Comment by jheer** [comment]
Thanks for asking! In the past there were multiple initialization methods, so the signature has some of the remnants of that.

Meanwhile, I just updated the `dericheInitZeroPad` method to include missing error correction loops (see the latest version), which makes use of the additional parameters.
