### ISSUE TITLE
How to obtain the density of a specific value?

### ISSUE THREAD

**Issue by liuzh-buaa** [uwdata/fast-kde#7]
In my opinion, the code returns a density array of `bins` size, where data are from `[lo, hi]`. (Is my understanding right?) However, I wonder whether I can obtain the density of a specific position.

For example, 
```
let d1 = density1d([1, 1, 5, 5, 6, 8]);
```

1) if I wonder the density of x=1 or x=5 or x=6 or x=8, how should I do?
2) if I wonder the density of x=0, how should I do?

Thank you very much.

**Comment by jheer** [comment]
Yes, density is calculated over a discrete set of bins. You can control the bin count using the `bins` option to `density1d()`.

The domain of values (over which the bins are defined) defaults to `[min - 3 * bandwidth, max + 3 * bandwidth]`, where `min` and `max` are the observed min and max values in the data. The factor 3 is simply the default value of the `pad` option, which you can set to another value if you like. Alternatively, you can use the `extent` option to explicitly set [lo, hi] values over which to calculate densities. Any values outside of the [lo, hi] extent are not included and so not accessible.

For more, see the code of the `density1d` method: https://github.com/uwdata/fast-kde/blob/main/src/density1d.js

The [`points` function](https://github.com/uwdata/fast-kde/blob/main/src/density1d.js#L22C3-L32C1) shows how to map a bin index and bin value to an original data value and corresponding PDF value. As each bin value corresponds to the probability mass for the entire bin, we scale these by the bin size (the `delta` value in the code) to get an approximate point-wise estimate.
